baseURL: "https://lingfengbetter.github.io/"
title: ling feng's blog
languageCode: zh
defaultContentLanguage: zh
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ling feng's blog
  description: "ling feng's blog"
  keywords: [Blog, ling feng]
  author: ling feng
  # author: ["Me", "You"] # multiple authors
  images: ["/assets/apple-touch-icon.png"]
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  busuanzi:
    enable: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/assets/favicon.ico"
    favicon16x16: "/assets/favicon-16x16.png"
    favicon32x32: "/assets/favicon-32x32.png"
    apple_touch_icon: "/assets/apple-touch-icon.png"
    #safari_pinned_tab: "<link / abs url>"

  label:
    text: "ling feng's blog"
    icon: /assets/apple-touch-icon.png
    iconHeight: 35

  pagination:
    pagerSize: 6
    path: "page"

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ling feng's blog
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "ling feng's blog"
    Content: never never never give up !

  socialIcons:
    - name: email
      url: "mailto:liulingfeng@mail.ioa.ac.cn"
    - name: github
      url: "https://github.com/lingfengbetter"

  #analytics:
    #google:
      #SiteVerificationTag: "XYZabc"
    #bing:
      #SiteVerificationTag: "XYZabc"
    #yandex:
      #SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/lingfengbetter/lingfengbetter.github.io/blob/main/content"
    Text: "提交修改建议" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: archives
      name: 归档
      url: /archives/
      weight: 10
    - identifier: categories
      name: 分类
      url: /categories/
      weight: 20
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 30
    - identifier: search
      name: 搜索
      url: /search/
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
  
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary